### ISSUE TITLE
suggest > geocode

### ISSUE THREAD

**Issue by jgravois** [oppoudel/react-geocoder#1]
greetings! 👋 _very_ cool project!

you'd probably generate even better results from our geocoding service if you used [`suggest()`](https://esri.github.io/arcgis-rest-js/api/geocoder/suggest/) instead of `geocode()` for your partial strings.

a bounding box filter (instead of tacking on "Baltimore, Md" manually) could improve output too.

```js

suggest("123 Mai", {
  params: { searchExtent: [-77,40,-75,38] } 
})
```
it'd require that you actually `geocode()` candidates once they've been selected, but that approach has worked quite well in https://github.com/Esri/esri-leaflet-geocoder.

either way, i'd like to link to this project from the rest-js doc. would that be okay with you?

**Comment by oppoudel** [comment]
Thank you for the suggestion. I will try it out. Sure, you can link it from rest-js docs.

**Comment by jgravois** [comment]
thanks so much and keep up the great work! 🎉

**Comment by oppoudel** [comment]
Made the suggested changes on last commit.

**Comment by jgravois** [comment]
excellent!  you're our very first [In the wild](https://www.npmjs.com/package/@esri/arcgis-rest-geocoder#in-the-wild) example.
